# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_type', models.CharField(max_length=50)),
                ('Brand_name', models.CharField(max_length=100)),
                ('RAM', models.CharField(max_length=15)),
                ('Storage_size', models.CharField(max_length=15)),
                ('Screen_size', models.CharField(max_length=10)),
                ('Cost', models.IntegerField()),
                ('Supplier', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchase_Date', models.DateTimeField(verbose_name=datetime.datetime(2017, 6, 25, 21, 45, 5, 200135, tzinfo=utc))),
                ('Amount_Paid', models.IntegerField()),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarpenstein.Customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarpenstein.Device')),
            ],
        ),
    ]
